### ISSUE TITLE
Feat Progression System Failed To Install

### ISSUE THREAD

**Issue by Anprionsa** [UnearthedArcana/Might_and_Guile#11]
Here are the logs. 

Used the EE Install Tool. Had an issue yesterday trying to install where the multkit wasn't installing properly, but I changed a few mods and it didn't give me that issue today. I'm not sure if it's because there is another mod messing with it (probably is) that isn't listed in the conflicts with either BWS or EE Tool. 

[SETUP-MIGHT_AND_GUILE.zip](https://github.com/UnearthedArcana/Might_and_Guile/files/2332782/SETUP-MIGHT_AND_GUILE.zip)
[Clean v1.3.ini.zip](https://github.com/UnearthedArcana/Might_and_Guile/files/2332783/Clean.v1.3.ini.zip)
[Bak-201808281803.zip](https://github.com/UnearthedArcana/Might_and_Guile/files/2332785/Bak-201808281803.zip)

**Comment by subtledoctor** [comment]
"Clean.v1.3.ini.zip"

Can't see any of that from a phone, but if you are trying to do this on v1.3, that component requires 1.4+ as stated in the readme.

**Comment by Anprionsa** [comment]
Sorry that v1.3 is actually just my compilation of mods and not the version of Might and Guile.

**Comment by Anprionsa** [comment]
Tried a new install with a few tweaks, but still had the same issue. 

ERROR: cannot convert al_code or %al_code% to an integer
ERROR: [might_and_guile/feats/d5_rfc1.spl] -> [override] Patching Failed (COPY) (Not_found)
