### ISSUE TITLE
Note for BWS / EE Setup / Project Infinity users

### ISSUE THREAD

**Issue by Darth-Cthoras** [UnearthedArcana/Might_and_Guile#15]
By default, particularly with Big World Setup / EE Mod Setup (Baldur's World Extended) installers, Might & Guile will automatically install *prior* to all other UI mods. This can break Might & Guile's Feat System ever since it ceased being a dialogue. Most prominent case in point is currently Lefreut's Enhanced UI for BG1EE, SoD, BG2EE and EET, which totally breaks it as no feats will show in the modified UI Lefreut installs. 

Solution: install Might & Guile's Feat System manually if necessary, *after* any other UI mods.

Alternative: a reversion to an earlier Might & Guile release which uses the dialogue box to choose feats, or a reversion in the source to that, would also suffice. M&G worked fine loaded PRIOR to Lefreut's in the past with that system of feat management.

**Comment by subtledoctor** [comment]
As discussed elsewhere, installing UI overhauls last is very bad practice.  Stuff like LeFreut's mod should be considered not different from an old-fashioned mod that does a lot of overwriting: install it first, so all that overwriting doesn't screw up other mods.  There are a number of mods that make small UI changes via patching code (this one, also Shadow Magic, Faiths & Powers, Deities of Faerun, maybe more).  LeFreut's and similar UI overhauls should always be installed prior to such mods.

I'm pretty sure Project Infinity already handles this quite well, and I think I have the order straight in my Mac Weidu Launcher.  As for Roxanne's BWS fork, it's up to her to do things the right way.

**Comment by Darth-Cthoras** [comment]
Completely understandable. The BWS was built upon the principle of installing components according to what they're modifying. Kit stuff comes right before UI stuff, which is last. At the time, BWS/EE Mod Setup were accounting for the dialogue system M&G *used* to have for feats. It just never got updated so that the Feat System & Multiclass Changes+Kits gets moved to the last section of install, after LeFreut. That can probably be fixed on both ends, I just wanted a note here for anyone else confused why M&G wasn't working in them with certain options.

**Comment by nickkeane** [comment]
Just an fyi if you didn't know or notice, but it looks like LeUI was moved a few days after this post in EE Mod Setup to be much earlier in the install list.

https://github.com/EE-Mod-Setup/EE-Mod-Setup/commit/1ac22cf12b202d50da295c0886731ab41e6c5323#diff-4d9fd966745a13c9b80110109c700985ec2f1ddd00d315dd5dc0683d18fdac7f

**Comment by Darth-Cthoras** [comment]
@nickkeane : Thanky for the heads up - due to the MASSIVE PAIN IN THE ARSE reinstalling BWS/EE tends to be, I only do it once a year, at best, and haven't done a new one since opening this issue. This is good information to have for my upcoming one, though, since I *do* plan on another one soonish so I get the latest content and fixes. As it typically takes me about a week and several restarts of the installation to get a working, viable install with the options I want, it's not something I do lightly or often.
