### ISSUE TITLE
Some installation/kit issues with BG2EE and EET

### ISSUE THREAD

**Issue by rahenry** [UnearthedArcana/Might_and_Guile#16]
Edit:
Actually I had not installed the Kensai component. It's flagged as deprecated in the .tp2. So it appears the problem is just that Berserker is overwriting Wizard Slayer, and leaving the original berserker untouched. Also the plain fighter description seems unchanged/unfinished. It doesn't list the available feats or anything like the thief description.
--------------------------------------------------------
I find that some kits/components don't install correctly on BG2EE (or EET). Specifically, the OG fighter kits such as Berserker and Kensai are unmodified. They don't gain feats, and seem to just have vanilla abilities. The trueclass Fighter works fine (gains feats etc.) but seems to still have the vanilla description. New fighter kits such as the Corsair work correctly. On BG1EE, everything works fine. Also I should note that I'm running Linux and installing in a case-insensitive ext4 partition, but I've installed many other mods without problems. I also tried in an ntfs partition with the same result. This is using a fresh install of BG2EE from the GoG (linux) installer.

Also I should note that there were no errors during installation.

[weidu.log](https://github.com/UnearthedArcana/Might_and_Guile/files/4322193/weidu.log)

**Comment by 4udr4n** [comment]
Same issue with EET on Windows. I'm trying to figure out if I have other mods conflicting, but cannot currently find any. I also have missing or partial descriptions for various bard songs, will attempt to catalogue these when I have time.

**Comment by rahenry** [comment]
I'm glad to hear I'm not crazy...! I still get the issue with a totally fresh install of BG2EE, but not with BGEE. I also found a somewhat similar issue with SR_revised: https://github.com/BartyMae/SR_Revised/issues/12 - you could try reproducing that if you are interested
