### ISSUE TITLE
Shadowdancer kit just not there

### ISSUE THREAD

**Issue by SJT555** [UnearthedArcana/Might_and_Guile#19]
Tried installing the latest version a few different ways and the Shadowdancer kit just isn't available at char creation.

Other mods are Scales of Balance, Spell Revisions and Tweaks Antology.

**Comment by SJT555** [comment]
In fact my Feats are broken too - Rogues are getting both their own feats and the warrior feats as well, and the Shadow Magic and Illusion Magic feats are absent...

**Comment by szaumoor** [comment]
Hmm...yeah, this is still happening on the most recent version.
