### ISSUE TITLE
Error Installing Might & Guile Multiclass Bards

### ISSUE THREAD

**Issue by nickkeane** [UnearthedArcana/Might_and_Guile#23]
I'm installing a pretty sizeable modpack using EE Mod Setup Tool and ran into an issue w/ M&G.

```
ERROR: [d5zclons.2da] -> [override/d5zclons.2da] Patching Failed (COPY) (Failure("resource [SPWI975.spl] not found for 'COPY'"))
ERROR: Failure("resource [SPWI975.spl] not found for 'COPY'")
Bard Overhaul: Multiclass Bards (Might and Guile) was not installed due to errors.
```

**Comment by GraionDilach** [comment]
This is coming from The Darkest Day and should be fixed in TDDz. As a workaround, pause the install of TDDz during your multimod installation and manually copy `TDD/SPL/SPWI975.spl` to the `override` folder.

**Comment by GraionDilach** [comment]
This got fixed in the TDD/TDDz version the EE Mod Setup Tool provides via https://github.com/EE-Mod-Setup/TDD/commit/9d9ef7c7b0cd1ef6380c92c43c8520c425ca448f.
